# Generated by Django 2.2 on 2022-12-02 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPartysModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=254, verbose_name='活动标题')),
                ('price', models.CharField(max_length=5, verbose_name='活动价格')),
                ('numbers', models.IntegerField(verbose_name='报名人数')),
                ('startime', models.DateTimeField(verbose_name='活动开始时间')),
                ('endtims', models.DateTimeField(verbose_name='活动截止时间')),
                ('playways', models.CharField(choices=[('1', '先到先得'), ('2', '双向选择'), ('3', '大数据匹配')], max_length=1, verbose_name='活动玩法')),
                ('tags', models.CharField(choices=[('1', '单身派对'), ('2', '英式下午茶'), ('3', '二次元')], max_length=3, verbose_name='默认标签')),
                ('inputag', models.CharField(max_length=60, verbose_name='输入标签')),
                ('pictures', models.ImageField(upload_to='', verbose_name='活动照片')),
            ],
            options={
                'verbose_name': '饭局活动表',
                'verbose_name_plural': '饭局活动表',
            },
        ),
    ]
